export const template_noOpacity = {
  "baseParamsList": [{
    "controlType": "slide",
    "label": "金属度",
    "max": "1",
    "min": "0.01",
    "paramName": "Metallic",
    "paramValue": "0"
  }, {
    "controlType": "slide",
    "label": "粗糙度",
    "max": "2",
    "min": "0",
    "paramName": "Roughness",
    "paramValue": "1"
  }, {
    "controlType": "slide",
    "label": "自发光",
    "max": "1",
    "min": "0",
    "paramName": "Emission",
    "paramValue": "0"
  }, {
    "controlType": "slide",
    "label": "法线强度",
    "max": "2",
    "min": "-2",
    "paramName": "Normal",
    "paramValue": "1"
  }],
  "colorList": [{
    "paramName": "BaseColor",
    "paramValue": ["14.058823529411764", "187.7372549019608", "221.87058823529412", "255.0"]
  }, {
    "paramName": "EmissionColor",
    "paramValue": ["255.0", "255.0", "255.0", "255.0"]
  }],
  "textureParamsList": [{
    "controlType": "switch",
    "label": "等比缩放",
    "max": "1",
    "min": "0",
    "paramName": "SwitchProportionalScale",
    "paramValue": "0"
  }, {
    "controlType": "slide",
    "label": "横向偏移",
    "max": "1",
    "min": "0",
    "paramName": "UVOffset_X",
    "paramValue": "0"
  }, {
    "controlType": "slide",
    "label": "纵向偏移",
    "max": "1",
    "min": "0",
    "paramName": "UVOffset_Y",
    "paramValue": "0"
  }, {
    "controlType": "slide",
    "label": "角度",
    "max": "360",
    "min": "0",
    "paramName": "UVRotation",
    "paramValue": "0",
    "unit": "°"
  }, {
    "controlType": "slide",
    "label": "缩放",
    "max": "2",
    "min": "0.5",
    "paramName": "UVScale",
    "paramValue": "1"
  }, {
    "controlType": "slide",
    "label": "横向缩放",
    "max": "2",
    "min": "0",
    "paramName": "UVScale_X",
    "paramValue": "1"
  }, {
    "controlType": "slide",
    "label": "纵向缩放",
    "max": "2",
    "min": "0",
    "paramName": "UVScale_Y",
    "paramValue": "1"
  }],
  "texturesList": [{
    "paramName": "BaseColorMap",
    "paramValue": "https://api.ourbim.com:11023/vjapi/userMaterialMap/Materials_PBR/T_White_Color.png"
  }, {
    "paramName": "MetallicMap",
    "paramValue": "https://api.ourbim.com:11023/vjapi/userMaterialMap/Materials_PBR/T_White_Linear.png"
  }, {
    "paramName": "RoughnessMap",
    "paramValue": "https://api.ourbim.com:11023/vjapi/userMaterialMap/Materials_PBR/T_MidGray_Linear.BMP"
  }, {
    "paramName": "NormalMap",
    "paramValue": "https://api.ourbim.com:11023/vjapi/userMaterialMap/Materials_PBR/T_Flat_Normal.png"
  }, {
    "paramName": "EmissionMap",
    "paramValue": "https://api.ourbim.com:11023/vjapi/userMaterialMap/Materials_PBR/T_White_Color.png"
  }]
}

export const template_opacity = {
  "baseParamsList": [{
    "controlType": "slide",
    "label": "金属度",
    "max": "1",
    "min": "0.01",
    "paramName": "Metallic",
    "paramValue": "0"
  }, {
    "controlType": "slide",
    "label": "粗糙度",
    "max": "2",
    "min": "0",
    "paramName": "Roughness",
    "paramValue": "1"
  }, {
    "controlType": "slide",
    "label": "自发光",
    "max": "1",
    "min": "0",
    "paramName": "Emission",
    "paramValue": "0"
  }, {
    "controlType": "slide",
    "label": "法线强度",
    "max": "2",
    "min": "-2",
    "paramName": "Normal",
    "paramValue": "1"
  }, {
    "controlType": "slide",
    "label": "透明度",
    "max": "1",
    "min": "0",
    "paramName": "Opacity",
    "paramValue": "0.5"
  }],
  "colorList": [{
    "paramName": "BaseColor",
    "paramValue": ["255.0", "255.0", "255.0", "255.0"]
  }, {
    "paramName": "EmissionColor",
    "paramValue": ["255.0", "255.0", "255.0", "255.0"]
  }],
  "textureParamsList": [{
    "controlType": "switch",
    "label": "等比缩放",
    "max": "1",
    "min": "0",
    "paramName": "SwitchProportionalScale",
    "paramValue": "0"
  }, {
    "controlType": "slide",
    "label": "横向偏移",
    "max": "1",
    "min": "0",
    "paramName": "UVOffset_X",
    "paramValue": "0"
  }, {
    "controlType": "slide",
    "label": "纵向偏移",
    "max": "1",
    "min": "0",
    "paramName": "UVOffset_Y",
    "paramValue": "0"
  }, {
    "controlType": "slide",
    "label": "角度",
    "max": "360",
    "min": "0",
    "paramName": "UVRotation",
    "paramValue": "0",
    "unit": "°"
  }, {
    "controlType": "slide",
    "label": "缩放",
    "max": "2",
    "min": "0.5",
    "paramName": "UVScale",
    "paramValue": "1"
  }, {
    "controlType": "slide",
    "label": "横向缩放",
    "max": "2",
    "min": "0",
    "paramName": "UVScale_X",
    "paramValue": "1"
  }, {
    "controlType": "slide",
    "label": "纵向缩放",
    "max": "2",
    "min": "0",
    "paramName": "UVScale_Y",
    "paramValue": "1"
  }],
  "texturesList": [{
    "paramName": "BaseColorMap",
    "paramValue": "https://api.ourbim.com:11023/vjapi/userMaterialMap/Materials_PBR/T_White_Color.png"
  }, {
    "paramName": "MetallicMap",
    "paramValue": "https://api.ourbim.com:11023/vjapi/userMaterialMap/Materials_PBR/T_White_Linear.png"
  }, {
    "paramName": "RoughnessMap",
    "paramValue": "https://api.ourbim.com:11023/vjapi/userMaterialMap/Materials_PBR/T_MidGray_Linear.BMP"
  }, {
    "paramName": "NormalMap",
    "paramValue": "https://api.ourbim.com:11023/vjapi/userMaterialMap/Materials_PBR/T_Flat_Normal.png"
  }, {
    "paramName": "EmissionMap",
    "paramValue": "https://api.ourbim.com:11023/vjapi/userMaterialMap/Materials_PBR/T_White_Color.png"
  }]
}